paths:
  raw: "./data/raw" # Directory for raw input PDF files
  processed: "./data/processed" # Directory for processed output IMG files
  archive: "./data/archive" # Directory for archived files


mongo:
  uri: "mongodb+srv://bk_db_user:v9tF48XQoI3g8Jz8@cluster0.ynj3gxs.mongodb.net/?appName=Cluster0"  # MongoDB connection URI (updated to hosted cluster)
  db: "invoice_db" # Database name
  collection_invoices: "invoices" # Main invoices collection
  collection_embeddings: "invoice_to_embeddings" # Embeddings collection

thresholds:
  arithmetic_tolerance: 0.01
  duplicate_similarity: 0.95
